alerting:
  github:
    repository: "BayuArga669/gatus"
    [cite_start]token: "$GITHUB_TOKEN" [cite: 124]
    default-alert:
      [cite_start]failure-threshold: 3 [cite: 129]
      [cite_start]success-threshold: 5 [cite: 129]
      [cite_start]send-on-resolved: true [cite: 129]

endpoints:
  - name: "Leantime"
    [cite_start]url: "http://$ALB_ENDPOINT" [cite: 126]
    [cite_start]interval: 30s [cite: 127]
    conditions:
      - [cite_start]"[STATUS] == 200" [cite: 127]
      - [cite_start]"[RESPONSE_TIME] < 300" [cite: 127]
    alerts:
      - type: github

  - name: "Gatus"
    [cite_start]url: "http://$ALB_ENDPOINT:8080" [cite: 126, 218]
    [cite_start]interval: 1m [cite: 128]
    conditions:
      - [cite_start]"[STATUS] == 200" [cite: 128]
      - [cite_start]"[RESPONSE_TIME] < 500" [cite: 128]
    alerts:
      - type: github
