name: LKS Deployment Pipeline

on:
  push:
    branches: [ master, main ]
    paths:
      - 'leantime/**'
      - 'gatus/**'
      - [cite_start]'.github/workflows/lks-deployment-pipeline.yml' [cite: 269, 270, 271, 272, 273]

jobs:
  deploy-gatus:
    [cite_start]name: Build and Deploy Gatus App [cite: 276, 277, 278]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          [cite_start]aws-region: us-east-1 [cite: 254, 256, 258]

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          [cite_start]ECR_REPOSITORY: lks-gatus [cite: 190]
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./gatus
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT [cite: 193, 276]

      - name: Render Amazon ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          [cite_start]task-definition: gatus/task-definition.json [cite: 131]
          [cite_start]container-name: lks-gatus-app [cite: 133]
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          [cite_start]service: gatus-service [cite: 239]
          [cite_start]cluster: lks-oss-cluster [cite: 225]
          wait-for-service-stability: true
        env:
          [cite_start]GITHUB_TOKEN: ${{ secrets.TOKEN }} [cite: 124, 260]
          [cite_start]ALB_ENDPOINT: ${{ secrets.ALB_ENDPOINT }} [cite: 259]
